### PR TITLE
Updated build.cake to implement deps.json transform (#55)

### PR DESCRIPTION
**Pull request by izaruba**
A solution for [#55](https://github.com/awaescher/RepoZ/issues/55)

This is probably not the most elegant way to do the JSON job, yet it works.

### CODE REVIEW

**Comment by awaescher** [comment]
@izaruba I am so thankful for your help. However, when I run the cake script, I still cannot run grr.exe or grrui.exe. Did you check this?

```
Error:
  An assembly specified in the application dependencies manifest (grr.deps.json) was not found:
    package: 'AsyncIO', version: '0.1.26'
    path: 'lib/netstandard1.3/AsyncIO.dll'
```

**Comment by izaruba** [comment]
> I still cannot run grr.exe or grrui.exe. Did you check this?

@awaescher that looks like `ReplaceRegexInFiles(outputDir.Path + "/**/*.deps.json", @"(?<="").*[/|\\](?=.*dll|.*exe)", "");` hasn't been executed. Will check.

**Comment by awaescher** [comment]
That line was commented out. Got it back in now. That part looks better:

```
          },
          "/clrjit.dll": {
            "fileVersion": "4.6.26919.2"
          },
```

The rest of the file looks good as well like the AsyncIO definition ...

```
    "AsyncIO/0.1.26": {
        "dependencies": {
          "NETStandard.Library": "2.0.3",
          "System.Net.NameResolution": "4.0.0"
        },
        "runtime": {
          "AsyncIO.dll": {
            "assemblyVersion": "0.1.25.0",
            "fileVersion": "0.1.25.0"
          }
        }
      },
```

... and its library path:

```
    "libraries": {
    "AsyncIO/0.1.26": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-CAYJtP918LYWgsM8YKmiz3uaAbAnv+Bj5HkMoQFVCo8GWIUE4Vib+ulpyIPSMkqeBpcfzcQ+iEuvlt/6eztG9g==",
      "path": ".",
      "hashPath": "asyncio.0.1.26.nupkg.sha512"
    },
```

However ...

```
Error:
  An assembly specified in the application dependencies manifest (grr.deps.json) was not found:
    package: 'AsyncIO', version: '0.1.26'
    path: 'AsyncIO.dll'
```

**Comment by izaruba** [comment]
I was only able to reproduce it if removed `AsyncIO.dll` from the `lib` folder. Otherwise works fine.
Could you please share the trace log (you need to set COREHOST_TRACE env. variable to 1)?

**Comment by awaescher** [comment]
I found out that you're right when testing the executable from its working directory.
However, running it from another directory (like for a global command line tool as grr) will fail.

screenshot 2018-12-05 at 12 55 13

**Comment by awaescher** [comment]
The trace (starting from `C:\Program Files\`) is: 

```
The rid fallback graph is: {
}
-- Listing probe configurations...
probe_config_t: probe=[] deps-dir-probe=[1]
Adding tpa entry: C:\Program Files\RepoZ\grr.dll, AssemblyVersion: , FileVersion:
Processing TPA for deps entry [AsyncIO, 0.1.26, AsyncIO.dll]
  Considering entry [AsyncIO/0.1.26/AsyncIO.dll], probe dir [], probe fx level:0, entry fx level:0
    Local path query did not exist C:\Program Files\RepoZ\AsyncIO.dll
    Skipping... not found in deps dir 'C:\Program Files\RepoZ\'
    Skipping... not found in probe dir ''
Error:
  An assembly specified in the application dependencies manifest (grr.deps.json) was not found:
    package: 'AsyncIO', version: '0.1.26'
    path: 'AsyncIO.dll'

C:\Program Files>

```

**Comment by awaescher** [comment]
Thanks @izaruba  for clarification. That working dir handling is what I found out as well. I came to the same thought of writing the runtimeconfig during the setup process but I might just throw all of that away and go back to the state I currently am. I'd like to show it with a sketch:

bat

That was the first approach I came up with but it has some disadvantages. I was very happy to find out about the probing path but after all this seems not the be the way to go. Just look at all the RegEx replacements we're throwing over the netcore json files during the build.

It feels wrong to me and to be honest the way the additionalProbingPath is specified and implemented is very unclear. Almost every bit I found on the net about that topic was from confused guys like me and contradictionary comments. And then there's you helping me out with a PR and finally throwing some light to StackOverflow questions. 


Thanks @izaruba, I wish I could help you out as well. Ping me if I can. For now, I'll think about all of that and maybe go back to the sketch approach and keep the fingers crossed for netcore 3.0.

**Pull request merged**
