### PR TITLE
upgrade deps & localization support

### PR DESCRIPTION
**Pull request by pedoc**
upgrade all dependencies over nuget
localization support(en_us & zh_cn)

### CODE REVIEW

**Comment by awaescher** [comment]
Thanks for contributing, @pedoc. I'll have a closer look at this soon. Timing's quite perfect, I prepared a release a few days ago.

**Comment by awaescher** [comment]
Thanks for your contribution, pedoc. Highly appreciated.
I found a few strings which are not translated yet. Would you help me out with a translatin to zh_cn?

**Comment by pedoc** [comment]
yes,i will reconfirm the string that needs to be translated.

**Comment by awaescher** [comment]
Alright, here we go then. Thanks in advance, mate.

```
    <system:String x:Key="Open in Windows File Explorer">In Windows Explorer öffnen</system:String>
    <system:String x:Key="Open in Windows PowerShell">In Windows Powershell öffnen</system:String>
    <system:String x:Key="Open in Windows Command Prompt">In Windows Eingabeaufforderung öffnen</system:String>
    <system:String x:Key="Open in Git Bash">In Git Bash öffnen</system:String>
    <system:String x:Key="Fetch">Git Fetch</system:String>
    <system:String x:Key="Pull">Git Pull</system:String>
    <system:String x:Key="Push">Git Push</system:String>
    <system:String x:Key="Checkout">Branch wechseln</system:String>
    <system:String x:Key="Ignore">Ignorieren</system:String>
```

**Comment by pedoc** [comment]
@awaescher 	cool,thanks for u work. plaease review this PR #85

**Comment by awaescher** [comment]
Good day, @pedoc. I have a few more translations for you, sorry. 

I already inserted them into the `zh-cn.xaml`. Would be cool if you could translate them for us. Thanks!


```
	<system:String x:Key="ScanMac">⚡ Scan mac</system:String>
	<system:String x:Key="Open in Finder">Open in Finder</system:String>
	<system:String x:Key="Open in Terminal">Open in Terminal</system:String>
	<system:String x:Key="Update hint">Version {0} is available.</system:String>
```

Btw, I removed the emojis in english and german. I suggest you should do in chinese as well if you don't mind.

**Comment by awaescher** [comment]
Any news on this, @pedoc?

**Comment by pedoc** [comment]
@awaescher sure,but I have been busy recently, so I need some time,sorry.

**Comment by awaescher** [comment]
No problem. Anyways, you can just give me the texts in here, I can put it into the source by myself.

**Pull request merged**
